package com.asio.tools.excelutils.model;

import java.io.Serializable;
import java.util.Date;

/**
 *
 * 此类为mybatis生成器自动生成，请勿手工修改任何内容！
 * 数据库对应表： property_feature_mapping
 */
public class PropertyFeatureMapping implements Serializable {
    /**
     * 备注：字段特征映射Id
     * 数据库字段：property_feature_mapping_key_id
     */
    private Long propertyFeatureMappingKeyId;

    /**
     * 备注：字段特征映射accessId
     * 数据库字段：property_feature_mapping_access_id
     */
    private String propertyFeatureMappingAccessId;

    /**
     * 备注：映射业务类型
     * 数据库字段：feature_business_type
     */
    private String featureBusinessType;

    /**
     * 备注：业务数据Id
     * 数据库字段：business_id
     */
    private Long businessId;

    /**
     * 备注：对象全路径
     * 数据库字段：bo_full_path
     */
    private String boFullPath;

    /**
     * 备注：映射字段名
     * 数据库字段：property_name
     */
    private String propertyName;

    /**
     * 备注：字段说明
     * 数据库字段：property_desc
     */
    private String propertyDesc;

    /**
     * 备注：映射类型
     * 数据库字段：feature_type
     */
    private String featureType;

    /**
     * 备注：映射值
     * 数据库字段：feature_rule
     */
    private String featureRule;

    /**
     * 备注：字典/枚举取值key属性
     * 数据库字段：target_key_field
     */
    private String targetKeyField;

    /**
     * 备注：字典/枚举取值value属性
     * 数据库字段：target_value_field
     */
    private String targetValueField;

    /**
     * 备注：优先级顺序
     * 数据库字段：sort
     */
    private Integer sort;

    /**
     * 备注：是否启用
     * 数据库字段：valid_flag
     */
    private Boolean validFlag;

    /**
     * 备注：创建人Id
     * 数据库字段：create_man_id
     */
    private Long createManId;

    /**
     * 备注：创建人名称
     * 数据库字段：create_man_name
     */
    private String createManName;

    /**
     * 备注：创建时间
     * 数据库字段：create_time
     */
    private Date createTime;

    /**
     * 备注：更新人Id
     * 数据库字段：update_man_id
     */
    private Long updateManId;

    /**
     * 备注：更新人名称
     * 数据库字段：update_man_name
     */
    private String updateManName;

    /**
     * 备注：是否被删除
     * 数据库字段：delete_flag
     */
    private Boolean deleteFlag;

    /**
     * 备注：修改时间
     * 数据库字段：db_update_time
     */
    private Date dbUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table property_feature_mapping
     */
    private static final long serialVersionUID = 1L;

    /**
     * 字段特征映射Id
     * @return property_feature_mapping_key_id 字段特征映射Id
     */
    public Long getPropertyFeatureMappingKeyId() {
        return propertyFeatureMappingKeyId;
    }

    /**
     * 字段特征映射Id
     * @param propertyFeatureMappingKeyId 字段特征映射Id
     */
    public void setPropertyFeatureMappingKeyId(Long propertyFeatureMappingKeyId) {
        this.propertyFeatureMappingKeyId = propertyFeatureMappingKeyId;
    }

    /**
     * 字段特征映射accessId
     * @return property_feature_mapping_access_id 字段特征映射accessId
     */
    public String getPropertyFeatureMappingAccessId() {
        return propertyFeatureMappingAccessId;
    }

    /**
     * 字段特征映射accessId
     * @param propertyFeatureMappingAccessId 字段特征映射accessId
     */
    public void setPropertyFeatureMappingAccessId(String propertyFeatureMappingAccessId) {
        this.propertyFeatureMappingAccessId = propertyFeatureMappingAccessId == null ? null : propertyFeatureMappingAccessId.trim();
    }

    /**
     * 映射业务类型
     * @return feature_business_type 映射业务类型
     */
    public String getFeatureBusinessType() {
        return featureBusinessType;
    }

    /**
     * 映射业务类型
     * @param featureBusinessType 映射业务类型
     */
    public void setFeatureBusinessType(String featureBusinessType) {
        this.featureBusinessType = featureBusinessType == null ? null : featureBusinessType.trim();
    }

    /**
     * 业务数据Id
     * @return business_id 业务数据Id
     */
    public Long getBusinessId() {
        return businessId;
    }

    /**
     * 业务数据Id
     * @param businessId 业务数据Id
     */
    public void setBusinessId(Long businessId) {
        this.businessId = businessId;
    }

    /**
     * 对象全路径
     * @return bo_full_path 对象全路径
     */
    public String getBoFullPath() {
        return boFullPath;
    }

    /**
     * 对象全路径
     * @param boFullPath 对象全路径
     */
    public void setBoFullPath(String boFullPath) {
        this.boFullPath = boFullPath == null ? null : boFullPath.trim();
    }

    /**
     * 映射字段名
     * @return property_name 映射字段名
     */
    public String getPropertyName() {
        return propertyName;
    }

    /**
     * 映射字段名
     * @param propertyName 映射字段名
     */
    public void setPropertyName(String propertyName) {
        this.propertyName = propertyName == null ? null : propertyName.trim();
    }

    /**
     * 字段说明
     * @return property_desc 字段说明
     */
    public String getPropertyDesc() {
        return propertyDesc;
    }

    /**
     * 字段说明
     * @param propertyDesc 字段说明
     */
    public void setPropertyDesc(String propertyDesc) {
        this.propertyDesc = propertyDesc == null ? null : propertyDesc.trim();
    }

    /**
     * 映射类型
     * @return feature_type 映射类型
     */
    public String getFeatureType() {
        return featureType;
    }

    /**
     * 映射类型
     * @param featureType 映射类型
     */
    public void setFeatureType(String featureType) {
        this.featureType = featureType == null ? null : featureType.trim();
    }

    /**
     * 映射值
     * @return feature_rule 映射值
     */
    public String getFeatureRule() {
        return featureRule;
    }

    /**
     * 映射值
     * @param featureRule 映射值
     */
    public void setFeatureRule(String featureRule) {
        this.featureRule = featureRule == null ? null : featureRule.trim();
    }

    /**
     * 字典/枚举取值key属性
     * @return target_key_field 字典/枚举取值key属性
     */
    public String getTargetKeyField() {
        return targetKeyField;
    }

    /**
     * 字典/枚举取值key属性
     * @param targetKeyField 字典/枚举取值key属性
     */
    public void setTargetKeyField(String targetKeyField) {
        this.targetKeyField = targetKeyField == null ? null : targetKeyField.trim();
    }

    /**
     * 字典/枚举取值value属性
     * @return target_value_field 字典/枚举取值value属性
     */
    public String getTargetValueField() {
        return targetValueField;
    }

    /**
     * 字典/枚举取值value属性
     * @param targetValueField 字典/枚举取值value属性
     */
    public void setTargetValueField(String targetValueField) {
        this.targetValueField = targetValueField == null ? null : targetValueField.trim();
    }

    /**
     * 优先级顺序
     * @return sort 优先级顺序
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * 优先级顺序
     * @param sort 优先级顺序
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * 是否启用
     * @return valid_flag 是否启用
     */
    public Boolean getValidFlag() {
        return validFlag;
    }

    /**
     * 是否启用
     * @param validFlag 是否启用
     */
    public void setValidFlag(Boolean validFlag) {
        this.validFlag = validFlag;
    }

    /**
     * 创建人Id
     * @return create_man_id 创建人Id
     */
    public Long getCreateManId() {
        return createManId;
    }

    /**
     * 创建人Id
     * @param createManId 创建人Id
     */
    public void setCreateManId(Long createManId) {
        this.createManId = createManId;
    }

    /**
     * 创建人名称
     * @return create_man_name 创建人名称
     */
    public String getCreateManName() {
        return createManName;
    }

    /**
     * 创建人名称
     * @param createManName 创建人名称
     */
    public void setCreateManName(String createManName) {
        this.createManName = createManName == null ? null : createManName.trim();
    }

    /**
     * 创建时间
     * @return create_time 创建时间
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * 创建时间
     * @param createTime 创建时间
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * 更新人Id
     * @return update_man_id 更新人Id
     */
    public Long getUpdateManId() {
        return updateManId;
    }

    /**
     * 更新人Id
     * @param updateManId 更新人Id
     */
    public void setUpdateManId(Long updateManId) {
        this.updateManId = updateManId;
    }

    /**
     * 更新人名称
     * @return update_man_name 更新人名称
     */
    public String getUpdateManName() {
        return updateManName;
    }

    /**
     * 更新人名称
     * @param updateManName 更新人名称
     */
    public void setUpdateManName(String updateManName) {
        this.updateManName = updateManName == null ? null : updateManName.trim();
    }

    /**
     * 是否被删除
     * @return delete_flag 是否被删除
     */
    public Boolean getDeleteFlag() {
        return deleteFlag;
    }

    /**
     * 是否被删除
     * @param deleteFlag 是否被删除
     */
    public void setDeleteFlag(Boolean deleteFlag) {
        this.deleteFlag = deleteFlag;
    }

    /**
     * 修改时间
     * @return db_update_time 修改时间
     */
    public Date getDbUpdateTime() {
        return dbUpdateTime;
    }

    /**
     * 修改时间
     * @param dbUpdateTime 修改时间
     */
    public void setDbUpdateTime(Date dbUpdateTime) {
        this.dbUpdateTime = dbUpdateTime;
    }
}

